### ISSUE TITLE
Support acceptable confidence in experiment criteria

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/etc3#135]
**Is your feature request related to a problem? Please describe.**
In addition to specifying rewards / objectives / indicators / requestCount -- allow specification of what is an acceptable level of confidence in computing a winner.

This field is intended to be interpreted by analytics service.

**Describe the solution you'd like**
```yaml
spec: {
  criteria: {
    confidence: // arbitrary json object  here...
  }
}
```
